### ISSUE TITLE
SSH Agent

### ISSUE THREAD

**Issue by Keoghan** [konsulting/porter#67]
Consider adding:

```sh
eval $(ssh-agent -s)
ssh-add /root/.ssh/id_rsa
```

to interactive containers

**Comment by rdarcy1** [comment]
If this is based on the user's .ssh directory, would be good to make the file name/path configurable.

**Comment by Keoghan** [comment]
I think that I'll add a config/user/bashrc which can be used to do things like this, then the user can customise the shell session easily too.

**Comment by rdarcy1** [comment]
Closed by #70
